<template lang="html">
  <div id="main-cont">
    <div id="title">
      <h1>SCREAMRACER</h1>
    </div>
    <div id="cont">
      <div id="myProgress">
        <img id="player-one" v-bind:style="{left: ((players[0].count/30000) * 100) + '%'}" :src="players[0].picture"
        class="scale-up-center">
      </div>
      <div id="myProgress">
        <img id="player-two" v-bind:style="{left: ((players[1].count/30000) * 100) + '%'}" :src="players[1].picture"
        class="scale-up-center">
      </div>
    </div>

  </div>
</template>
<script>
import Dbmeter from 'decibel-meter'
import swal from 'sweetalert'

const dbmeter = new Dbmeter('unique-id')

export default {
  data () {
    return {
      playerKey: localStorage.getItem('playerKey'),
      playerIdx: Number(localStorage.getItem('playerIdx'))
    }
  },
  firebase () {
    return {
      players: this.$db.ref('screamracer/room1')
    }
  },
  methods: {
    listening () {
      const seth = (val) => {
        this.$db.ref('screamracer/room1').child(this.playerKey).child('count').set(val)
      }

      dbmeter.connectTo(0)
      dbmeter.listen()
      dbmeter.on('sample', (dB, percent, value) => {
        let winner = null
        if (percent > 50) {
          seth(this.players[this.playerIdx].count += percent)

          if (this.players[0].count >= 30000 || this.players[1].count >= 30000) {
            if (this.players[0].count > this.players[1].count) {
              winner = this.players[0].username
              this.players[0].count = 30000
            } else {
              winner = this.players[1].username
              this.players[1].count = 30000
            }
            swal(`WINNER: ${winner}`)
            dbmeter.stopListening()
            this.$db.ref('screamracer').child('finished').set(true)
          }
        }
      })
    }
  },
  mounted () {
    this.listening()
    this.$db.ref('screamracer').child('finished').set(false)
    this.$db.ref('screamracer').on('value', snap => {
      let isFinished = snap.val().finished
      localStorage.clear()
      if (isFinished) {
        this.$db.ref('screamracer/room1').set(null)
        this.$db.ref('screamracer').child('start').set(null)
        this.$db.ref('screamracer').child('finished').set(null)
        this.$router.push('/')
      }
    })
  }
}
</script>

<style lang="css">
  #myProgress {
    width: 100%;
    background-color: #333;
    margin: 32px 0;
    position: relative;
    border-radius: 100px;
  }

  #main-cont {
    background: #222;
    width: 100%;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
  }

.scale-up-center {
  -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
          animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

  #cont {
    width: 80%;
  }
  
  #start {
    display: none;
  }

  #title h1 {
    font-family: 'Monoton', cursive;
    font-size: 48px;
    color: #fafafa;
  }

  #player-one, #player-two {
    position: relative;
    left: 100px;
    width: auto;
    height: 128px;
    border-radius: 100%;
    background-color: #4CAF50;
  }
/* ----------------------------------------------
 * Generated by Animista on 2017-11-3 15:28:8
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

</style>
